# Generated by Django 2.0.3 on 2018-03-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio (opcional)')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
                'verbose_name': 'Propiedad',
            },
        ),
        migrations.CreateModel(
            name='PropImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='propiedades', verbose_name='Imagen')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='props.Prop')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
                'verbose_name': 'Imagen',
            },
        ),
    ]
